apiVersion: v1
kind: Service
metadata:
  name: cicdcont-service
spec:
  selector:
    app: cicdapp  # Match the label in the Pod definition
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 31500
  type: NodePort